### ISSUE TITLE
False positive?

### ISSUE THREAD

**Issue by marcelo321** [defparam/smuggler#13]
Hello,

I'm trying to use the tool but I don't know if I'm getting false positives or I'm just doing everything wrong.

I am receiving the following alert from smuggler:

```
[xnprespace-08]: Potential CLTE Issue Found - POST @ https://redacted.com/asdsad?code=asdasd - default.py
[CRITICAL]     : CLTE Payload: .... redacted
```

So I went to the payloads folder, copy pasted the payload in repeater, put the right host and everything and sent it to turbo intruder to test it.

All I get is code 405s.. over and over. Not a single different response code. I'm not sure if I'm doing this correctly or what smuggler detected to alert it. Does it alert code 405s? Am I doing something wrong?

What response code did smuggler got to alert it as possible http smuggling case?

 Please anyone help me!

**Comment by marcelo321** [comment]
I get this alert with all the `xnprespace-*` ones.

**Comment by shelld3v** [comment]
Hi @marcelo321, here is an answer from my knowledge:
1. First, Turbo Intruder is not a good HTTP smuggling testing tool if you are going to test the main website of a company because that website got billions of connections and requests every day, every hour. Although Turbo Intruder sends requests very fast, but it will never able to poison your next request when another request from anywhere around the world has sent to the server before your next request, so you just only able to poison other users' requests.

2. As the author said in the README, **smuggler** can have false positives, this is a fact of most of testing tools, special when HTTP smuggling is very tricky! 

Finding a way to confirm this bug is the best way, if you don't know how to do it, watch James Kettle's talk last year at Back hat

**Comment by defparam** [comment]
Nicely Put @shelld3v ,

I would also like to add that the main goal for this tool and repo is to find potential request smuggling targets. When smuggler flags an asset its job is done. How you use that information is up to you. Teaching everyone how to use the payload to conduct a successful desync attack is out of scope for the purpose of this tool and git repo.

**Comment by marcelo321** [comment]
@shelld3v what is the best option to test for HTTP smuggling if it is not turbo intruder? that's recommended by albinowax.

I know it can have false positives, but to be a false positive it must have detected a weird code response or something, is there a way to know which code or why it detected it as a possible case of HTTP smuggling? that way the manual analysis is easier to do.

**Comment by defparam** [comment]
@marcelo321 ,

This is not the place to discuss how to actively exploit HTTP Request Smuggling. If there is a bug in the tool that is causing false positives feel free to open another issue describing the bug. Thread locked

Best,
@defparam
