### ISSUE TITLE
Want to catch the requests in burp

### ISSUE THREAD

**Issue by Hacker-DaoXin** [defparam/smuggler#4]
I have been exported http and https to burp's intercept
Commands:
export http_proxy="http://127.0.0.1:8080" 
export https_proxy="http://127.0.0.1:8080"

And I was trying to analyze the requests I've sent through burp http history, but I didn't get it, should I export another type of protocol or I should make it work.

My environments are qualified.
BTW, really great talk on Nahamcon, I learned a lot from it, thank you.

**Comment by defparam** [comment]
Hey @Hacker-DaoXin ,

Thanks for the kind words! The issue here is I’m not using a formal HTTP request library with proxy support. Instead I am using python socket objects. If HTTP proxy support is required it would have to be rolled into the script (which it currently isn’t). Another strategy is to dump socket data sent/recv’d into a file to be imported. This would also require modifying the script.

Hope this helps,
Evan

**Comment by Hacker-DaoXin** [comment]
Thanks so much for the explanation, hope you'll have a great summer.
